### ISSUE TITLE
Strange lines in dashboard nvim

### ISSUE THREAD

**Issue by Bogdan-Torkhov** [maxmx03/dracula.nvim#13]
screen: https://www.mediafire.com/view/aqbleom8wko6n22/Screenshot_from_2023-04-29_09-07-51.png/file

idk after what it came.

**Comment by maxmx03** [comment]
It seems like you are experiencing some strange lines in your nvim dashboard and you are not sure how they appeared. Although this is not related to the dracula.nvim plugin, I can still offer some suggestions to try and fix the issue.

One possible solution is to exclude the dashboard file type from the list of files where indent lines are displayed. To do this, you can add the following line to indentline configuration:

[#566](https://github.com/lukas-reineke/indent-blankline.nvim/issues/566)

```lua
vim.g.indentLine_fileTypeExclude = {'dashboard'}
```

**Comment by Bogdan-Torkhov** [comment]
These didn't helped

**Comment by Bogdan-Torkhov** [comment]
Don't helped!!!

**Comment by maxmx03** [comment]
you are doing something wrong in your config

```lua
vim.g.indent_blankline_filetype_exclude = { 'dashboard', 'lspinfo', 'packer', 'checkhealth', 'help', 'man', 'NvimTree' }
```

![20230509_04h42m30s_grim](https://user-images.githubusercontent.com/50273941/237028773-d6d973f9-cb6d-4873-91fb-1663eab03486.png)

![20230509_04h46m14s_grim](https://user-images.githubusercontent.com/50273941/237029552-ecc0b688-4bae-4194-bf74-0831dbe67d2e.png)
