### ISSUE TITLE
O tema não ta funcionando

### ISSUE THREAD

**Issue by diegolima-dev** [maxmx03/dracula.nvim#25]
Não sei por que mas não rola de jeito nenhuma, testei outros temas do dracula de outros repositorios e funciona, mas não faço ideia o do pq que o seu não funciona, segue uns prints de como fica com o seu instalado e com outro, já tentei usando o codigo que você recomanda e fica do mesmo jeito

![2024-03-08_19-03](https://github.com/maxmx03/dracula.nvim/assets/122759453/3b1f781d-9de5-4a15-88b4-ce800b387468)
![2024-03-08_19-03_1](https://github.com/maxmx03/dracula.nvim/assets/122759453/4feb283c-3156-4315-8319-ab39e6ccb3bf)
![2024-03-08_19-04](https://github.com/maxmx03/dracula.nvim/assets/122759453/df20084d-8d27-4d83-ae14-27b5650f2f1f)
![2024-03-08_19-04_1](https://github.com/maxmx03/dracula.nvim/assets/122759453/d9fa6ac4-f173-43a5-b323-a79915a13d2b)

**Comment by maxmx03** [comment]
Bem, eu testei o colorscheme no neovim stable e neovim nightly e parecer estar funcionando corretamente.

`archlinux container`

![20240309_15h37m42s_grim](https://github.com/maxmx03/dracula.nvim/assets/50273941/d9fa5f9b-8734-4357-a7b6-fceb1bf190ff)

`archlinux container`

![20240309_15h45m19s_grim](https://github.com/maxmx03/dracula.nvim/assets/50273941/9db7b19a-0063-42cf-ab70-67857f366343)

**Comment by diegolima-dev** [comment]
Consegui aqui, tem nada de errado com o seu tema, eu só tinha que colocar isso no options.lua 

`set.termguicolors = true`

🤡 kkkkkk estranho que varios temas rodam sem isso
