### ISSUE TITLE
nvim-cmp border customization

### ISSUE THREAD

**Issue by gokayburuc** [maxmx03/dracula.nvim#26]
Cmp window border tranparency feature is available? How can i customize these gray borders and change them to dracula colors? There is black and gray borders in my terminal with default configurations.

![Screenshot from 2024-03-27 23-09-13](https://github.com/maxmx03/dracula.nvim/assets/20437751/60096c92-de0a-40bc-bc92-ff1073f10b33)

Thanks in advance.

**Comment by maxmx03** [comment]
```lua
   vim.opt.pumblend = 10         -- enables pseudo-transparency

   local function border(hl_name)
      return {
          { '╭', hl_name },
          { '─', hl_name },
          { '╮', hl_name },
          { '│', hl_name },
          { '╯', hl_name },
          { '─', hl_name },
          { '╰', hl_name },
          { '│', hl_name },
        }
   end

  cmp.setup {
    formatting = {
        window = {
        ompletion = {
           col_offset = -3,
           side_padding = 0,
           border = border 'WinSeparator', -- fix border
        },
        documentation = {
        border = border 'WinSeparator',
     },
   },
}
```

![Captura de tela 2024-03-28 113422](https://github.com/maxmx03/dracula.nvim/assets/50273941/6fb96069-4609-4779-bffc-fc76100c7640)
