### ISSUE TITLE
mason customization

### ISSUE THREAD

**Issue by gokayburuc** [maxmx03/dracula.nvim#27]
Need Mason support. Mason still black and gray. Need dracula color customizations.

![Screenshot from 2024-03-27 23-08-59](https://github.com/maxmx03/dracula.nvim/assets/20437751/d5f61c5b-2d14-493a-b544-f6c3bd6d7ed4)

**Comment by maxmx03** [comment]
I have already set the background color for `NormalFloat`, and `MasonNormal` is linking to `NormalFloat`. Perhaps **Tmux** is causing this problem.

```yml
    - name: NormalFloat
      fg: base0
      bg: base04
```

Possible Fix:

`.tmux.config`

```tmux
set -g default-terminal "tmux-256color"
```

`bashrc`

```bash
if [ -z "$TMUX" ]; then
    export TERM="xterm-256color"
fi
```
