### ISSUE TITLE
Want to help you

### ISSUE THREAD

**Issue by Bogdan-Torkhov** [maxmx03/dracula.nvim#5]
Hello, your plugin is amazing, but i have some bugs and one feature request. Feature is that i want to change all red colors to purple. And i have some bugs with transparency.
These is a link to the video where i show bugs that i founded: https://www.mediafire.com/file/rqgju265qygsdih/Screencast_from_2023-03-31_14-56-53.webm/file

1 is transparent bug
2 is numbers bug

And can you give me your discord, maybe i want to help you with developing of these plugin.

**Comment by maxmx03** [comment]
```lua
local c = require 'dracula.palettes'
```

Regarding transparency, it is currently as I wanted it to be, with only the code area being transparent. The nvim-tree is not transparent as it might be easier for users to see folders and such. However, it would be possible to make everything transparent as it ultimately comes down to personal preference.

If you want to customize, you can follow this example:
```lua
hl(0, "Normal", { fg = c.fg, bg = 'NONE' })
hl(0, "NormalFloat", { fg = c.fg, bg = 'NONE' })
hl(0, "SignColumn", { fg = 'NONE', bg = 'NONE' })
hl(0, "CursorLineNr", { fg = c.pink, bg = 'NONE' })
hl(0, "LineNr", { fg = c.pink, bg = 'NONE' })
```

Regarding colors, I could add an option for users to customize the colors of dracula.nvim. However, it's worth noting that red is not heavily used in the Dracula color scheme, except for diagnostics and search.

```lua
hl(0, "IncSearch", { fg = c.purple, bg = 'NONE' })
```

**Comment by Bogdan-Torkhov** [comment]
> 

hl function no't found :(

**Comment by Bogdan-Torkhov** [comment]
Can you send me the code with my params,pls

**Comment by maxmx03** [comment]
```lua
local c = require 'dracula.palettes'
local hl = vim.api.nvim_set_hl
```

```lua
hl(0, "Normal", { fg = c.fg, bg = 'NONE' })
hl(0, "NormalFloat", { fg = c.fg, bg = 'NONE' })
hl(0, "SignColumn", { fg = 'NONE', bg = 'NONE' })
hl(0, "CursorLineNr", { fg = c.pink, bg = 'NONE' })
hl(0, "LineNr", { fg = c.pink, bg = 'NONE' })
hl(0, "IncSearch", { fg = c.purple, bg = 'NONE' })
hl(0, "Error", { fg = c.purple, bg = 'NONE', bold=true, })
hl(0, "DiagnosticVirtualTextError", { fg = c.purple, bg = c.blended_purple })
hl(0, "DiagnosticError", { fg = c.purple, bg = 'NONE' })
```

**Comment by Bogdan-Torkhov** [comment]
```lua
local dracula_status, dracula = pcall(require, "dracula")
if not dracula_status then
	return
end

local dracula_color_status, color = pcall(require, "dracula.palettes")
if not dracula_color_status then
	return
end

local hl_status, hl = pcall(require, "vim.api.nvim_set_hl")
if not hl_status then
	return
end
-- colors
hl(0, "Normal", { fg = color.fg, bg = "NONE" })
hl(0, "NormalFloat", { fg = color.fg, bg = "NONE" })
hl(0, "SignColumn", { fg = "NONE", bg = "NONE" })
hl(0, "CursorLineNr", { fg = color.pink, bg = "NONE" })
hl(0, "LineNr", { fg = color.pink, bg = "NONE" })
hl(0, "IncSearch", { fg = color.purple, bg = "NONE" })
hl(0, "Error", { fg = color.purple, bg = "NONE", bold = true })
hl(0, "DiagnosticVirtualTextError", { fg = color.purple, bg = color.blended_purple })
hl(0, "DiagnosticError", { fg = color.purple, bg = "NONE" })
-- theme setup
dracula.setup({ soft = false, transparent = true })
```
These is my config and now transparency fully don't work and lazy steal red

**Comment by maxmx03** [comment]
```lua
-- theme setup
dracula.setup({ soft = false, transparent = true })

vim.cmd 'colorscheme dracula'

-- colors
hl(0, "Normal", { fg = color.fg, bg = "NONE" })
hl(0, "NormalFloat", { fg = color.fg, bg = "NONE" })
hl(0, "SignColumn", { fg = "NONE", bg = "NONE" })
hl(0, "CursorLineNr", { fg = color.pink, bg = "NONE" })
hl(0, "LineNr", { fg = color.pink, bg = "NONE" })
hl(0, "IncSearch", { fg = color.purple, bg = "NONE" })
hl(0, "Error", { fg = color.purple, bg = "NONE", bold = true })
hl(0, "DiagnosticVirtualTextError", { fg = color.purple, bg = color.blended_purple })
hl(0, "DiagnosticError", { fg = color.purple, bg = "NONE" })
```

or

```lua
vim.api.nvim_create_autocmd('ColorScheme', {
 callback = function()
   local c = require 'dracula.palettes'
   local hl = vim.api.nvim_set_hl

   hl(0, "Normal", { fg = color.fg, bg = "NONE" })
   hl(0, "NormalFloat", { fg = color.fg, bg = "NONE" })
   hl(0, "SignColumn", { fg = "NONE", bg = "NONE" })
   hl(0, "CursorLineNr", { fg = color.pink, bg = "NONE" })
   hl(0, "LineNr", { fg = color.pink, bg = "NONE" })
   hl(0, "IncSearch", { fg = color.purple, bg = "NONE" })
   hl(0, "Error", { fg = color.purple, bg = "NONE", bold = true })
   hl(0, "DiagnosticVirtualTextError", { fg = color.purple, bg = color.blended_purple })
   hl(0, "DiagnosticError", { fg = color.purple, bg = "NONE" })
 end
})
```

**Comment by maxmx03** [comment]
Hello, I have created a new branch, and I would like you to test it to see if everything is working correctly. In this new branch, you can customize the colors of dracula.nvim.

```lua
 'maxmx03/dracula.nvim',
    branch = 'customize-colors',
    lazy = false,
    priority = 1000,
    config = function()
      local dracula = require 'dracula'

      dracula.setup {
        soft = false,
        transparent = true,
        colors = function(colors)
          return {
            red = colors.purple,
            blended_red = colors.blended_purple,
            error = colors.purple,
          }
        end,
      }

      vim.cmd 'colorscheme dracula'
    end,

```

or 

```lua
      local dracula = require 'dracula'
      local colors = require 'dracula.palettes'


      dracula.setup {
        soft = false,
        transparent = true,
        colors = {
          red = colors.purple,
          blended_red = colors.blended_purple,
          error = colors.purple,
        },
      }
```

**Comment by Bogdan-Torkhov** [comment]
All colors are now white
screen:https://www.mediafire.com/view/r6waxmhal2flbof/Screenshot_from_2023-03-31_18-20-29.png/file

**Comment by maxmx03** [comment]
what about now?

**Comment by Bogdan-Torkhov** [comment]
Lazy is red(screen: https://www.mediafire.com/view/zubp0dfxrrrm68t/Screenshot_from_2023-03-31_18-37-25.png/file) and transparency don't work on tree

**Comment by Bogdan-Torkhov** [comment]
Then will fix?

**Comment by Bogdan-Torkhov** [comment]
Nothing changed, the name in lazy is still red and tree window isn't transparent

**Comment by Bogdan-Torkhov** [comment]
:(

**Comment by maxmx03** [comment]
it's working here.

![Captura de tela de 2023-03-31 13-28-00](https://user-images.githubusercontent.com/50273941/229177260-d2554d3c-7aae-41a9-8134-59d0f605093a.png)

**Comment by Bogdan-Torkhov** [comment]
Screncast: http://www.mediafire.com/file/4hsgh8foijc9zpm/Screencast_from_2023-03-31_19-27-21.webm

**Comment by Bogdan-Torkhov** [comment]
Any ideas. And i want not only lazy but all red stuff change to purple. And don't forget about tree window transparency

**Comment by maxmx03** [comment]
Did you change the dracula.nvim branch to 'customize-colors'.

![Captura de tela de 2023-03-31 13-35-07](https://user-images.githubusercontent.com/50273941/229178806-062c2527-0c83-4f7a-9481-4cd10f1bb17a.png)

**Comment by Bogdan-Torkhov** [comment]
> 

Yes, i have all updates

**Comment by Bogdan-Torkhov** [comment]
https://www.mediafire.com/view/w8nu2445zt4bkl2/Screenshot_from_2023-03-31_19-36-57.png/file

**Comment by Bogdan-Torkhov** [comment]
```lua
local dracula_status, dracula = pcall(require, "dracula")
if not dracula_status then
	return
end

local dracula_color_status, color = pcall(require, "dracula.palettes")
if not dracula_color_status then
	return
end

local hl_status, hl = pcall(require, "vim.api.nvim_set_hl")
if not hl_status then
	return
end

-- theme setup
dracula.setup({
	soft = false,
	transparent = true,
	colors = function(colors)
		return {
			red = colors.purple,
			blended_red = colors.blended_purple,
			error = colors.purple,
		}
	end,
	callback = function(colors)
		hl(0, "LazyH1", { fg = colors.purple, bg = colors.blended_purple })
		hl(0, "NormalFloat", { fg = colors.fg, bg = "NONE" })
	end,
})
```
These is my now config

**Comment by maxmx03** [comment]
you dont need to import `vim.api.nvim_set_hl`, `vim` is a global variable
you can use just like this

```lua
vim.api.nvim_set_hl(0, "LazyH1", { fg = colors.purple, bg = colors.blended_purple })
vim.api.nvim_set_hl(0, "NormalFloat", { fg = colors.fg, bg = "NONE" })
```

**Comment by Bogdan-Torkhov** [comment]
And how to fully change all red to purple?

**Comment by maxmx03** [comment]
here how: https://github.com/maxmx03/nvim/blob/main/lua/config/plugins.lua

![Captura de tela de 2023-03-31 14-03-08](https://user-images.githubusercontent.com/50273941/229184500-c9d2cc2d-3d21-4c73-bed9-39f3ec5578ad.png)
![Captura de tela de 2023-03-31 14-03-02](https://user-images.githubusercontent.com/50273941/229184502-4e0c82ab-e893-465f-b5c2-bcef96f9674a.png)

![Captura de tela de 2023-03-31 14-03-24](https://user-images.githubusercontent.com/50273941/229184495-b19bd90e-efea-47f0-9d40-780d60ba5155.png)

**Comment by Bogdan-Torkhov** [comment]
Cool!!! Goodby

**Comment by Bogdan-Torkhov** [comment]
And will you merge these to main?

**Comment by Bogdan-Torkhov** [comment]
And i also want iundent blankline(plugin) purple color

**Comment by Bogdan-Torkhov** [comment]
And can telescope have transparency?

**Comment by maxmx03** [comment]
yes.

```lua
vim.api.nvim_set_hl('NormalFloat', { fg = colors.fg, bg = 'NONE' })
```

**Comment by maxmx03** [comment]
> And will you merge these to main?

yep

**Comment by Bogdan-Torkhov** [comment]
Error : Error detected while processing /home/deusbog/.config/nvim/init.lua:
E5113: Error while calling lua chunk: ....local/share/nvim/lazy/lazy.nvim/lua/lazy/core/cache.lua:172: ...sbog/.c
onfig/nvim/lua/plugins-configs/dracula-config.lua:18: unexpected symbol near ','
stack traceback:
        [C]: in function 'error'
        ....local/share/nvim/lazy/lazy.nvim/lua/lazy/core/cache.lua:172: in function <....local/share/nvim/lazy/l
azy.nvim/lua/lazy/core/cache.lua:166>
        [C]: in function 'require'
        /home/deusbog/.config/nvim/init.lua:15: in main chunk

**Comment by Bogdan-Torkhov** [comment]
```lua
local dracula_status, dracula = pcall(require, "dracula")
if not dracula_status then
	return
end

-- theme setup
dracula.setup({
	soft = false,
	transparent = true,
	colors = function(colors)
		return {
			red = colors.purple,
			blended_red = colors.blended_purple,
			error = colors.purple,
		}
	end,
	callback = function(colors)
		vim.api.nvim_set_hl(0, "NvimTreeNormal", { fg = colors.fg, bg = "NONE" }),
		vim.api.nvim_set_hl(0, "NormalFloat", { fg = colors.fg, bg = "NONE" }),
	end,
})
```
config

**Comment by Bogdan-Torkhov** [comment]
??? Error detected while processing /home/deusbog/.config/nvim/init.lua:
E5113: Error while calling lua chunk: ....local/share/nvim/lazy/lazy.nvim/lua/lazy/core/cache.lua:172: ...sbog/.c
onfig/nvim/lua/plugins-configs/dracula-config.lua:18: unexpected symbol near ','
stack traceback:
[C]: in function 'error'
....local/share/nvim/lazy/lazy.nvim/lua/lazy/core/cache.lua:172: in function <....local/share/nvim/lazy/l
azy.nvim/lua/lazy/core/cache.lua:166>
[C]: in function 'require'
/home/deusbog/.config/nvim/init.lua:15: in main chunk

Have these error

**Comment by Bogdan-Torkhov** [comment]
Fixed

**Comment by Bogdan-Torkhov** [comment]
And what about indent blankline(plugin)? Can I set purple color to it?

**Comment by Bogdan-Torkhov** [comment]
???

**Comment by maxmx03** [comment]
You can find all highlight groups here [dracula.toml](https://github.com/maxmx03/dracula.nvim/blob/master/dracula.toml) or read [indent-blankline](https://github.com/lukas-reineke/indent-blankline.nvim/blob/master/doc/indent_blankline.txt) docs to find them.
dont forget to read the [how to customize dracula](https://github.com/maxmx03/dracula.nvim/blob/master/CUSTOMIZE.md)
### Hope that helps. Have a great day!

**Comment by Bogdan-Torkhov** [comment]
```lua
local dracula_status, dracula = pcall(require, "dracula")
if not dracula_status then
	return
end

-- theme setup
dracula.setup({
	soft = false,
	transparent = true,
	colors = function(colors)
		return { red = colors.purple, blended_red = colors.blended_purple }
	end,
	callback = function(colors)
		vim.api.nvim_set_hl(0, "NvimTreeNormal", { fg = colors.fg, bg = "NONE" })
		vim.api.nvim_set_hl(0, "NormalFloat", { fg = colors.fg, bg = "NONE" })
		vim.api.nvim_set_hl(0, "IndentBlanklineChar", { fg = colors.fg, bg = "NONE" })
		vim.api.nvim_set_hl(0, "IndentBlanklineSpaceChar", { fg = colors.fg, bg = "NONE" })
		vim.api.nvim_set_hl(0, "IndentBlanklineSpaceCharBlankline", { fg = colors.fg, bg = "NONE" })
		vim.api.nvim_set_hl(0, "IndentBlanklineContextChar", { fg = colors.fg, bg = "NONE" })
		vim.api.nvim_set_hl(0, "IndentBlanklineContextSpaceChar", { fg = colors.fg, bg = "NONE" })
		vim.api.nvim_set_hl(0, "IndentBlanklineContextStart", { fg = colors.fg, bg = "NONE" })
	end,
})
```
These is my config and indent blankline is white
What to do?

**Comment by Bogdan-Torkhov** [comment]
Fixed. Changed fg to purple

**Comment by Bogdan-Torkhov** [comment]
Hey. Have another issue(not with your plugin) how you fixed vim global not found?
