### ISSUE TITLE
Small color changes (opinionated) 

### ISSUE THREAD

**Issue by MuhametSmaili** [maxmx03/dracula.nvim#8]
You did a great job on this theme, kudos to you. Shame that it was not merged directly in the Dracula repository. 

I have some suggestions that I think can improve more:

## Imrpove the LspReference (cursor hold color)

The 
- `LspRefernceText` 
- `LspReferenceRead`
- `LspReferenceWrite`

Right now has the color `float_bg`. I think it would be better if the color is different, something that you can see easily because the dark is not visible. Same in the visual studio code it is not dark it is somehow greenish.
Here you can see how I changed the color, I made the color to this: `#426646` (I took it with a color picker, maybe they have modified the green color in the visual studio code but not sure, have not checked)

Here is how it is now (left `vscode` right `neovim` when you hold cursor):
![image](https://user-images.githubusercontent.com/51492002/230002514-83eb2a50-8f2a-4626-8d33-79b4b7b99dbd.png)

Here is how it looks, after changing to the color mentioned above:
![image](https://user-images.githubusercontent.com/51492002/230002746-eb371e90-80c4-4207-b5cf-3373d59bc107.png)

**Comment by maxmx03** [comment]
try use blended_green to see how it looks.

```lua
local colors = require('dracula.palettes')

dracula.setup {
 override = {
  LspReferenceRead = { bg = colors.blended_green}, -- or colors.selection
  LspReferenceText = { bg = colors.blended_green}, -- or colors.selection
  LspReferenceWrite = { bg = colors.blended_green}, -- or colors.selection
 }
}
```

i never tested LspReferenceRead because i use plugin like [vim-illuminate](https://github.com/RRethy/vim-illuminate)

**Comment by MuhametSmaili** [comment]
> try use blended_green to see how it looks.

Yes, I think this is the color, you can make also this default if you want it to be the same as `code`.

Left `vscode` right `neovim`:

![image](https://user-images.githubusercontent.com/51492002/230271283-3128e732-0bbf-4982-8053-562a365f3029.png)


> I never tested LspReferenceRead because I use plugins like [vim-illuminate](https://github.com/RRethy/vim-illuminate)

 I did not know about that plugin. But [I am using the built-i](https://github.com/MuhametSmaili/neovim/blob/main/lua/smaili/plugins/lsp/init.lua#LL93C5-L109C8)n feature which is working fine for me until now. 

I consider this issue closed because you have the color in place, it is your choice if you want to make `blended_green` as default or not. 
Thank you
