### ISSUE TITLE
fix: cmp colors

### ISSUE THREAD

**Issue by MuhametSmaili** [maxmx03/dracula.nvim#9]
Currently, the cmp colors are not as they should be. In [dracula/vim ](https://github.com/dracula/vim/blob/master/after/plugin/dracula.vim#LL157C3-L186C48) you can see the colors are completely different. 
For example, the `text` in the cmp is `pink` which should be `white`. Also, the colors are not the same as in the `vscode` too, 

Here I wrote a basic color change that should be similar to other editors.

```
 CmpItemKindSnippet ='fg'
 CmpItemKindText = 'fg'
 CmpItemAbbrDeprecated = 'error'
 CmpItemKindVariable = 'purple - i'
 CmpItemKindFunction = 'link:@function'
 CmpItemKindMethod = 'link:@method'
 CmpItemKindConstructor = 'cyan'
 CmpItemKindClass = 'cyan'
 CmpItemKindEnum = 'pink'
 CmpItemKindEnumMember = 'purple'
 CmpItemKindInterface = 'link:@type'
 CmpItemKindStruct = 'link:@storageclass'


```

I did not write everything, needs rechecking with `vscode` and `dracula/vim`. If you want and are the same opinion I can create a `PR`, or you can check it.

The most important one, 
Text -> fg
deprecated -> error
snippet -> fg.

The text is pink which makes it important but is not, and should not attract our eyes to read it first.

Thanks in advance

**Comment by maxmx03** [comment]
Thank you for raising this issue. I believe that the colors used for the kind icons should match the code. While Dracula/Vim and VS Code use different colors, my implementation of Dracula.nvim may not use the same colors as either of them.

here an example:

![Captura de tela de 2023-04-07 19-22-34](https://user-images.githubusercontent.com/50273941/230686404-c899f46e-f455-4de0-9a01-aa52f2a49bd3.png)

**Comment by MuhametSmaili** [comment]
I do not know what this example has to do with `CMP` 

> Thank you for raising this issue. I believe that the colors used for the kind icons should match the code. While Dracula/Vim and VS Code use different colors, my implementation of Dracula.nvim may not use the same colors as either of them.
> 
> here an example:
> 
> ![Captura de tela de 2023-04-07 19-22-34](https://user-images.githubusercontent.com/50273941/230686404-c899f46e-f455-4de0-9a01-aa52f2a49bd3.png)

I do not understand what does the example you gave has to do with what I am saying. 
You are showing the colors inside `enum` and `lsp-saga`, coding colors. 
I am talking about CMP (completion engine) :

![image](https://user-images.githubusercontent.com/51492002/230724039-f726628f-9ab6-4e09-bdb8-349d4d02d3b9.png)

As you can see in the image above.

**Comment by maxmx03** [comment]
The example I showed earlier was from Lspsaga. What both **Lspsaga** and **cmp** have in common is that they both use **lspkind** icons. If you look closely at the example, you'll see that the Direction enum has the same color as the icons used in **lspsaga**. This is the same color that **cmp** uses.

Here are the code snippets for **cmp** and **lspsaga**, respectively:

cmp

    hl(0, "CmpItemKindEnum", { link = '@type' })
    hl(0, "CmpItemKindEnumMember", { link = '@constant' })

lspsaga

    hl(0, "SagaWinbarEnum", { link = '@type' })
    hl(0, "SagaWinbarEnumMember", { link = '@constant' })

**Comment by maxmx03** [comment]
By the way, I forgot to mention earlier that I actually updated the Dracula.nvim colorscheme based on the issue you reported. I double-checked and revised the colors for lspsaga, navic, and cmpkind to make sure everything is in order.

[commit](https://github.com/maxmx03/dracula.nvim/commit/3f707ba1651e59d79e8ccc66b17d1f43b961023e)
